### ISSUE TITLE
Part 3 

### ISSUE THREAD

**Issue by oplikos** [P2fryang/markdown-parse#1]
[a]  (b.com)

![image description](an-image.jpeg)

[link content](a-link.html)

![image](https://user-images.githubusercontent.com/44330982/154375156-d127fa9c-fdbe-4b21-8ca3-536f074e8185.png)

in order to fix this issue make sure if you don't find the close bracket to inform the program to continue not to break
where you can find more test I've run for your code

https://github.com/oplikos/markdown-parse/tree/main/markdown-parse-main-other-group

[test-file15.md](https://github.com/P2fryang/markdown-parse/files/8084337/test-file15.md)

**Comment by P2fryang** [comment]
Issue fixed here: https://github.com/P2fryang/markdown-parse/commit/f2d5016fa230d52d6de0d2a212515f98d6d250a3
